package com.albionservant.integration.market;

import java.util.Map;

/**
 * Exact Albion Online UniqueName mappings for gear shown by CraftPanel.
 *
 * The mapping stores the T4 base identifier. Tier and enchantment are applied
 * when a concrete market lookup is requested.
 */
public final class GearMarketItemData {

    private static final Map<String, String> BASE_IDS = Map.ofEntries(
            Map.entry("Arcane Staff", "T4_MAIN_ARCANESTAFF"),
            Map.entry("Arclight Blasters", "T4_2H_DUALCROSSBOW_CRYSTAL"),
            Map.entry("Arctic Staff", "T4_2H_FROSTSTAFF_CRYSTAL"),
            Map.entry("Armor of Valor", "T4_ARMOR_PLATE_AVALON"),
            Map.entry("Assassin Hood", "T4_HEAD_LEATHER_SET3"),
            Map.entry("Assassin Jacket", "T4_ARMOR_LEATHER_SET3"),
            Map.entry("Assassin Shoes", "T4_SHOES_LEATHER_SET3"),
            Map.entry("Astral Aegis", "T4_OFF_SHIELD_AVALON"),
            Map.entry("Astral Staff", "T4_2H_ARCANESTAFF_CRYSTAL"),
            Map.entry("Avalonian Axe", "T4_2H_TOOL_AXE_AVALON"),
            Map.entry("Avalonian Cape", "T4_CAPEITEM_AVALON"),
            Map.entry("Avalonian Fishing Rod", "T4_2H_TOOL_FISHINGROD_AVALON"),
            Map.entry("Avalonian Pickaxe", "T4_2H_TOOL_PICK_AVALON"),
            Map.entry("Avalonian Sickle", "T4_2H_TOOL_SICKLE_AVALON"),
            Map.entry("Avalonian Siege Hammer", "T4_2H_TOOL_SIEGEHAMMER_AVALON"),
            Map.entry("Avalonian Skinning Knife", "T4_2H_TOOL_KNIFE_AVALON"),
            Map.entry("Avalonian Stone Hammer", "T4_2H_TOOL_HAMMER_AVALON"),
            Map.entry("Bag", "T4_BAG"),
            Map.entry("Battle Bracers", "T4_2H_KNUCKLES_SET2"),
            Map.entry("Battleaxe", "T4_MAIN_AXE"),
            Map.entry("Bear Paws", "T4_2H_DUALAXE_KEEPER"),
            Map.entry("Bedrock Mace", "T4_MAIN_ROCKMACE_KEEPER"),
            Map.entry("Black Monk Stave", "T4_2H_COMBATSTAFF_MORGANA"),
            Map.entry("Blazing Staff", "T4_2H_INFERNOSTAFF_MORGANA"),
            Map.entry("Blight Staff", "T4_2H_NATURESTAFF_HELL"),
            Map.entry("Bloodletter", "T4_MAIN_RAPIER_MORGANA"),
            Map.entry("Bloodmoon Staff", "T4_2H_SHAPESHIFTER_MORGANA"),
            Map.entry("Blueflame Torch", "T4_OFF_TORCH_CRYSTAL"),
            Map.entry("Boltcasters", "T4_2H_DUALCROSSBOW_HELL"),
            Map.entry("Boots of Valor", "T4_SHOES_PLATE_AVALON"),
            Map.entry("Bow", "T4_2H_BOW"),
            Map.entry("Bow of Badon", "T4_2H_BOW_KEEPER"),
            Map.entry("Brawler Gloves", "T4_2H_KNUCKLES_SET1"),
            Map.entry("Brecilien Cape", "T4_CAPEITEM_FW_BRECILIEN"),
            Map.entry("Bridgewatch Cape", "T4_CAPEITEM_FW_BRIDGEWATCH"),
            Map.entry("Bridled Fury", "T4_2H_DAGGER_KATAR_AVALON"),
            Map.entry("Brimstone Staff", "T4_2H_FIRESTAFF_HELL"),
            Map.entry("Broadsword", "T4_MAIN_SWORD"),
            Map.entry("Caerleon Cape", "T4_CAPEITEM_FW_CAERLEON"),
            Map.entry("Caitiff Shield", "T4_OFF_SHIELD_HELL"),
            Map.entry("Camlann Mace", "T4_2H_MACE_MORGANA"),
            Map.entry("Cape", "T4_CAPE"),
            Map.entry("Carrioncaller", "T4_2H_HALBERD_MORGANA"),
            Map.entry("Carving Sword", "T4_2H_CLEAVER_HELL"),
            Map.entry("Celestial Censer", "T4_OFF_CENSER_AVALON"),
            Map.entry("Chillhowl", "T4_MAIN_FROSTSTAFF_AVALON"),
            Map.entry("Clarent Blade", "T4_MAIN_SCIMITAR_MORGANA"),
            Map.entry("Claws", "T4_2H_CLAWPAIR"),
            Map.entry("Claymore", "T4_2H_CLAYMORE"),
            Map.entry("Cleric Cowl", "T4_HEAD_CLOTH_SET2"),
            Map.entry("Cleric Robe", "T4_ARMOR_CLOTH_SET2"),
            Map.entry("Cleric Sandals", "T4_SHOES_CLOTH_SET2"),
            Map.entry("Cowl of Purity", "T4_HEAD_CLOTH_AVALON"),
            Map.entry("Crossbow", "T4_2H_CROSSBOW"),
            Map.entry("Cryptcandle", "T4_OFF_LAMP_UNDEAD"),
            Map.entry("Crystal Reaper", "T4_2H_SCYTHE_CRYSTAL"),
            Map.entry("Cultist Cowl", "T4_HEAD_CLOTH_MORGANA"),
            Map.entry("Cultist Robe", "T4_ARMOR_CLOTH_MORGANA"),
            Map.entry("Cultist Sandals", "T4_SHOES_CLOTH_MORGANA"),
            Map.entry("Cursed Skull", "T4_2H_SKULLORB_HELL"),
            Map.entry("Cursed Staff", "T4_MAIN_CURSEDSTAFF"),
            Map.entry("Dagger", "T4_MAIN_DAGGER"),
            Map.entry("Dagger Pair", "T4_2H_DAGGERPAIR"),
            Map.entry("Damnation Staff", "T4_2H_CURSEDSTAFF_MORGANA"),
            Map.entry("Dawnsong", "T4_2H_FIRE_RINGPAIR_AVALON"),
            Map.entry("Daybreaker", "T4_MAIN_SPEAR_LANCE_AVALON"),
            Map.entry("Deathgivers", "T4_2H_DUALSICKLE_UNDEAD"),
            Map.entry("Demon Armor", "T4_ARMOR_PLATE_HELL"),
            Map.entry("Demon Boots", "T4_SHOES_PLATE_HELL"),
            Map.entry("Demon Cape", "T4_CAPEITEM_DEMON"),
            Map.entry("Demon Helmet", "T4_HEAD_PLATE_HELL"),
            Map.entry("Demonfang", "T4_MAIN_DAGGER_HELL"),
            Map.entry("Demonic Staff", "T4_2H_DEMONICSTAFF"),
            Map.entry("Divine Staff", "T4_2H_DIVINESTAFF"),
            Map.entry("Double Bladed Staff", "T4_2H_DOUBLEBLADEDSTAFF"),
            Map.entry("Dreadstorm Monarch", "T4_MAIN_MACE_CRYSTAL"),
            Map.entry("Druid Cowl", "T4_HEAD_CLOTH_KEEPER"),
            Map.entry("Druid Robe", "T4_ARMOR_CLOTH_KEEPER"),
            Map.entry("Druid Sandals", "T4_SHOES_CLOTH_KEEPER"),
            Map.entry("Druidic Staff", "T4_MAIN_NATURESTAFF_KEEPER"),
            Map.entry("Dual Swords", "T4_2H_DUALSWORD"),
            Map.entry("Earthrune Staff", "T4_2H_SHAPESHIFTER_KEEPER"),
            Map.entry("Energy Shaper", "T4_2H_CROSSBOW_CANNON_AVALON"),
            Map.entry("Enigmatic Staff", "T4_2H_ENIGMATICSTAFF"),
            Map.entry("Evensong", "T4_2H_ARCANE_RINGPAIR_AVALON"),
            Map.entry("Exalted Staff", "T4_2H_HOLYSTAFF_CRYSTAL"),
            Map.entry("Eye of Secrets", "T4_OFF_ORB_MORGANA"),
            Map.entry("Facebreaker", "T4_OFF_SPIKEDSHIELD_MORGANA"),
            Map.entry("Fallen Staff", "T4_2H_HOLYSTAFF_HELL"),
            Map.entry("Fiend Cowl", "T4_HEAD_CLOTH_HELL"),
            Map.entry("Fiend Robe", "T4_ARMOR_CLOTH_HELL"),
            Map.entry("Fiend Sandals", "T4_SHOES_CLOTH_HELL"),
            Map.entry("Fire Staff", "T4_MAIN_FIRESTAFF"),
            Map.entry("Fisherman Backpack", "T4_BACKPACK_GATHERER_FISH"),
            Map.entry("Fisherman Cap", "T4_HEAD_GATHERER_FISH"),
            Map.entry("Fisherman Garb", "T4_ARMOR_GATHERER_FISH"),
            Map.entry("Fisherman Workboots", "T4_SHOES_GATHERER_FISH"),
            Map.entry("Fishing Rod", "T4_2H_TOOL_FISHINGROD"),
            Map.entry("Fists of Avalon", "T4_2H_KNUCKLES_AVALON"),
            Map.entry("Flamewalker Staff", "T4_MAIN_FIRESTAFF_CRYSTAL"),
            Map.entry("Forcepulse Bracers", "T4_2H_KNUCKLES_CRYSTAL"),
            Map.entry("Forge Hammers", "T4_2H_DUALHAMMER_HELL"),
            Map.entry("Forgebark Staff", "T4_MAIN_NATURESTAFF_CRYSTAL"),
            Map.entry("Fort Sterling Cape", "T4_CAPEITEM_FW_FORTSTERLING"),
            Map.entry("Frost Staff", "T4_MAIN_FROSTSTAFF"),
            Map.entry("Galatine Pair", "T4_2H_DUALSCIMITAR_UNDEAD"),
            Map.entry("Glacial Staff", "T4_2H_GLACIALSTAFF"),
            Map.entry("Glaive", "T4_2H_GLAIVE"),
            Map.entry("Grailseeker", "T4_2H_QUARTERSTAFF_AVALON"),
            Map.entry("Graveguard Armor", "T4_ARMOR_PLATE_UNDEAD"),
            Map.entry("Graveguard Boots", "T4_SHOES_PLATE_UNDEAD"),
            Map.entry("Graveguard Helmet", "T4_HEAD_PLATE_UNDEAD"),
            Map.entry("Great Arcane Staff", "T4_2H_ARCANESTAFF"),
            Map.entry("Great Cursed Staff", "T4_2H_CURSEDSTAFF"),
            Map.entry("Great Fire Staff", "T4_2H_FIRESTAFF"),
            Map.entry("Great Frost Staff", "T4_2H_FROSTSTAFF"),
            Map.entry("Great Hammer", "T4_2H_HAMMER"),
            Map.entry("Great Holy Staff", "T4_2H_HOLYSTAFF"),
            Map.entry("Great Nature Staff", "T4_2H_NATURESTAFF"),
            Map.entry("Greataxe", "T4_2H_AXE"),
            Map.entry("Grovekeeper", "T4_2H_RAM_KEEPER"),
            Map.entry("Guardian Armor", "T4_ARMOR_PLATE_SET3"),
            Map.entry("Guardian Boots", "T4_SHOES_PLATE_SET3"),
            Map.entry("Guardian Helmet", "T4_HEAD_PLATE_SET3"),
            Map.entry("Halberd", "T4_2H_HALBERD"),
            Map.entry("Hallowfall", "T4_MAIN_HOLYSTAFF_AVALON"),
            Map.entry("Hammer", "T4_MAIN_HAMMER"),
            Map.entry("Hand of Justice", "T4_2H_HAMMER_AVALON"),
            Map.entry("Harvester Backpack", "T4_BACKPACK_GATHERER_FIBER"),
            Map.entry("Harvester Cap", "T4_HEAD_GATHERER_FIBER"),
            Map.entry("Harvester Garb", "T4_ARMOR_GATHERER_FIBER"),
            Map.entry("Harvester Workboots", "T4_SHOES_GATHERER_FIBER"),
            Map.entry("Heavy Crossbow", "T4_2H_CROSSBOWLARGE"),
            Map.entry("Heavy Mace", "T4_2H_MACE"),
            Map.entry("Hellfire Hands", "T4_2H_KNUCKLES_HELL"),
            Map.entry("Hellion Hood", "T4_HEAD_LEATHER_HELL"),
            Map.entry("Hellion Jacket", "T4_ARMOR_LEATHER_HELL"),
            Map.entry("Hellion Shoes", "T4_SHOES_LEATHER_HELL"),
            Map.entry("Hellspawn Staff", "T4_2H_SHAPESHIFTER_HELL"),
            Map.entry("Helmet of Valor", "T4_HEAD_PLATE_AVALON"),
            Map.entry("Heretic Cape", "T4_CAPEITEM_HERETIC"),
            Map.entry("Heron Spear", "T4_MAIN_SPEAR_KEEPER"),
            Map.entry("Hoarfrost Staff", "T4_MAIN_FROSTSTAFF_KEEPER"),
            Map.entry("Holy Staff", "T4_MAIN_HOLYSTAFF"),
            Map.entry("Hood of Tenacity", "T4_HEAD_LEATHER_AVALON"),
            Map.entry("Hunter Hood", "T4_HEAD_LEATHER_SET2"),
            Map.entry("Hunter Jacket", "T4_ARMOR_LEATHER_SET2"),
            Map.entry("Hunter Shoes", "T4_SHOES_LEATHER_SET2"),
            Map.entry("Icicle Staff", "T4_2H_ICEGAUNTLETS_HELL"),
            Map.entry("Incubus Mace", "T4_MAIN_MACE_HELL"),
            Map.entry("Infernal Scythe", "T4_2H_SCYTHE_HELL"),
            Map.entry("Infernal Staff", "T4_2H_INFERNOSTAFF"),
            Map.entry("Infinity Blade", "T4_MAIN_SWORD_CRYSTAL"),
            Map.entry("Iron-clad Staff", "T4_2H_IRONCLADEDSTAFF"),
            Map.entry("Ironroot Staff", "T4_MAIN_NATURESTAFF_AVALON"),
            Map.entry("Jacket of Tenacity", "T4_ARMOR_LEATHER_AVALON"),
            Map.entry("Judicator Armor", "T4_ARMOR_PLATE_KEEPER"),
            Map.entry("Judicator Boots", "T4_SHOES_PLATE_KEEPER"),
            Map.entry("Judicator Helmet", "T4_HEAD_PLATE_KEEPER"),
            Map.entry("Keeper Cape", "T4_CAPEITEM_KEEPER"),
            Map.entry("Kingmaker", "T4_2H_CLAYMORE_AVALON"),
            Map.entry("Knight Armor", "T4_ARMOR_PLATE_SET2"),
            Map.entry("Knight Boots", "T4_SHOES_PLATE_SET2"),
            Map.entry("Knight Helmet", "T4_HEAD_PLATE_SET2"),
            Map.entry("Leering Cane", "T4_OFF_JESTERCANE_HELL"),
            Map.entry("Lifecurse Staff", "T4_MAIN_CURSEDSTAFF_UNDEAD"),
            Map.entry("Lifetouch Staff", "T4_MAIN_HOLYSTAFF_MORGANA"),
            Map.entry("Light Crossbow", "T4_MAIN_1HCROSSBOW"),
            Map.entry("Lightcaller", "T4_2H_SHAPESHIFTER_AVALON"),
            Map.entry("Longbow", "T4_2H_LONGBOW"),
            Map.entry("Lumberjack Backpack", "T4_BACKPACK_GATHERER_WOOD"),
            Map.entry("Lumberjack Cap", "T4_HEAD_GATHERER_WOOD"),
            Map.entry("Lumberjack Garb", "T4_ARMOR_GATHERER_WOOD"),
            Map.entry("Lumberjack Workboots", "T4_SHOES_GATHERER_WOOD"),
            Map.entry("Lymhurst Cape", "T4_CAPEITEM_FW_LYMHURST"),
            Map.entry("Mace", "T4_MAIN_MACE"),
            Map.entry("Mage Cowl", "T4_HEAD_CLOTH_SET3"),
            Map.entry("Mage Robe", "T4_ARMOR_CLOTH_SET3"),
            Map.entry("Mage Sandals", "T4_SHOES_CLOTH_SET3"),
            Map.entry("Malevolent Locus", "T4_2H_ENIGMATICORB_MORGANA"),
            Map.entry("Martlock Cape", "T4_CAPEITEM_FW_MARTLOCK"),
            Map.entry("Mercenary Hood", "T4_HEAD_LEATHER_SET1"),
            Map.entry("Mercenary Jacket", "T4_ARMOR_LEATHER_SET1"),
            Map.entry("Mercenary Shoes", "T4_SHOES_LEATHER_SET1"),
            Map.entry("Miner Backpack", "T4_BACKPACK_GATHERER_ORE"),
            Map.entry("Miner Cap", "T4_HEAD_GATHERER_ORE"),
            Map.entry("Miner Garb", "T4_ARMOR_GATHERER_ORE"),
            Map.entry("Miner Workboots", "T4_SHOES_GATHERER_ORE"),
            Map.entry("Mistcaller", "T4_OFF_HORN_KEEPER"),
            Map.entry("Mistpiercer", "T4_2H_BOW_AVALON"),
            Map.entry("Morgana Cape", "T4_CAPEITEM_MORGANA"),
            Map.entry("Morning Star", "T4_2H_FLAIL"),
            Map.entry("Muisak", "T4_OFF_DEMONSKULL_HELL"),
            Map.entry("Nature Staff", "T4_MAIN_NATURESTAFF"),
            Map.entry("Oathkeepers", "T4_2H_DUALMACE_AVALON"),
            Map.entry("Occult Staff", "T4_2H_ARCANESTAFF_HELL"),
            Map.entry("Permafrost Prism", "T4_2H_ICECRYSTAL_UNDEAD"),
            Map.entry("Phantom Twinblade", "T4_2H_DOUBLEBLADEDSTAFF_CRYSTAL"),
            Map.entry("Pickaxe", "T4_2H_TOOL_PICK"),
            Map.entry("Pike", "T4_2H_SPEAR"),
            Map.entry("Polehammer", "T4_2H_POLEHAMMER"),
            Map.entry("Primal Staff", "T4_2H_SHAPESHIFTER_SET3"),
            Map.entry("Prowling Staff", "T4_2H_SHAPESHIFTER_SET1"),
            Map.entry("Quarrier Backpack", "T4_BACKPACK_GATHERER_ROCK"),
            Map.entry("Quarrier Cap", "T4_HEAD_GATHERER_ROCK"),
            Map.entry("Quarrier Garb", "T4_ARMOR_GATHERER_ROCK"),
            Map.entry("Quarrier Workboots", "T4_SHOES_GATHERER_ROCK"),
            Map.entry("Quarterstaff", "T4_2H_QUARTERSTAFF"),
            Map.entry("Rampant Staff", "T4_2H_NATURESTAFF_KEEPER"),
            Map.entry("Ravenstrike Cestus", "T4_2H_KNUCKLES_MORGANA"),
            Map.entry("Realmbreaker", "T4_2H_AXE_AVALON"),
            Map.entry("Redemption Staff", "T4_2H_HOLYSTAFF_UNDEAD"),
            Map.entry("Rift Glaive", "T4_2H_GLAIVE_CRYSTAL"),
            Map.entry("Robe of Purity", "T4_ARMOR_CLOTH_AVALON"),
            Map.entry("Rootbound Staff", "T4_2H_SHAPESHIFTER_SET2"),
            Map.entry("Rotcaller Staff", "T4_MAIN_CURSEDSTAFF_CRYSTAL"),
            Map.entry("Royal Armor", "T4_ARMOR_PLATE_ROYAL"),
            Map.entry("Royal Boots", "T4_SHOES_PLATE_ROYAL"),
            Map.entry("Royal Cowl", "T4_HEAD_CLOTH_ROYAL"),
            Map.entry("Royal Helmet", "T4_HEAD_PLATE_ROYAL"),
            Map.entry("Royal Hood", "T4_HEAD_LEATHER_ROYAL"),
            Map.entry("Royal Jacket", "T4_ARMOR_LEATHER_ROYAL"),
            Map.entry("Royal Robe", "T4_ARMOR_CLOTH_ROYAL"),
            Map.entry("Royal Sandals", "T4_SHOES_CLOTH_ROYAL"),
            Map.entry("Royal Shoes", "T4_SHOES_LEATHER_ROYAL"),
            Map.entry("Sacred Scepter", "T4_OFF_TALISMAN_AVALON"),
            Map.entry("Sandals of Purity", "T4_SHOES_CLOTH_AVALON"),
            Map.entry("Sarcophagus", "T4_OFF_TOWERSHIELD_UNDEAD"),
            Map.entry("Satchel of Insight", "T4_BAG_INSIGHT"),
            Map.entry("Scholar Cowl", "T4_HEAD_CLOTH_SET1"),
            Map.entry("Scholar Robe", "T4_ARMOR_CLOTH_SET1"),
            Map.entry("Scholar Sandals", "T4_SHOES_CLOTH_SET1"),
            Map.entry("Shadowcaller", "T4_MAIN_CURSEDSTAFF_AVALON"),
            Map.entry("Shield", "T4_OFF_SHIELD"),
            Map.entry("Shoes of Tenacity", "T4_SHOES_LEATHER_AVALON"),
            Map.entry("Sickle", "T4_2H_TOOL_SICKLE"),
            Map.entry("Siege Hammer (regular)", "T4_2H_TOOL_SIEGEHAMMER"),
            Map.entry("Siegebow", "T4_2H_CROSSBOWLARGE_MORGANA"),
            Map.entry("Skinner Backpack", "T4_BACKPACK_GATHERER_HIDE"),
            Map.entry("Skinner Cap", "T4_HEAD_GATHERER_HIDE"),
            Map.entry("Skinner Garb", "T4_ARMOR_GATHERER_HIDE"),
            Map.entry("Skinner Workboots", "T4_SHOES_GATHERER_HIDE"),
            Map.entry("Skinning Knife", "T4_2H_TOOL_KNIFE"),
            Map.entry("Skystrider Bow", "T4_2H_BOW_CRYSTAL"),
            Map.entry("Smuggler Cape", "T4_CAPEITEM_SMUGGLER"),
            Map.entry("Soldier Armor", "T4_ARMOR_PLATE_SET1"),
            Map.entry("Soldier Boots", "T4_SHOES_PLATE_SET1"),
            Map.entry("Soldier Helmet", "T4_HEAD_PLATE_SET1"),
            Map.entry("Soulscythe", "T4_2H_TWINSCYTHE_HELL"),
            Map.entry("Spear", "T4_MAIN_SPEAR"),
            Map.entry("Specter Hood", "T4_HEAD_LEATHER_UNDEAD"),
            Map.entry("Specter Jacket", "T4_ARMOR_LEATHER_UNDEAD"),
            Map.entry("Specter Shoes", "T4_SHOES_LEATHER_UNDEAD"),
            Map.entry("Spiked Gauntlets", "T4_2H_KNUCKLES_SET3"),
            Map.entry("Spirithunter", "T4_2H_HARPOON_HELL"),
            Map.entry("Staff of Balance", "T4_2H_ROCKSTAFF_KEEPER"),
            Map.entry("Stalker Hood", "T4_HEAD_LEATHER_MORGANA"),
            Map.entry("Stalker Jacket", "T4_ARMOR_LEATHER_MORGANA"),
            Map.entry("Stalker Shoes", "T4_SHOES_LEATHER_MORGANA"),
            Map.entry("Stillgaze Staff", "T4_2H_SHAPESHIFTER_CRYSTAL"),
            Map.entry("Stone Hammer", "T4_2H_TOOL_HAMMER"),
            Map.entry("Taproot", "T4_OFF_TOTEM_KEEPER"),
            Map.entry("Thetford Cape", "T4_CAPEITEM_FW_THETFORD"),
            Map.entry("Timelocked Grimoire", "T4_OFF_TOME_CRYSTAL"),
            Map.entry("Tombhammer", "T4_2H_HAMMER_UNDEAD"),
            Map.entry("Tome of Spells", "T4_OFF_BOOK"),
            Map.entry("Torch", "T4_OFF_TORCH"),
            Map.entry("Trinity Spear", "T4_2H_TRIDENT_UNDEAD"),
            Map.entry("Truebolt Hammer", "T4_2H_HAMMER_CRYSTAL"),
            Map.entry("Twin Slayers", "T4_2H_DAGGERPAIR_CRYSTAL"),
            Map.entry("Unbreakable Ward", "T4_OFF_SHIELD_CRYSTAL"),
            Map.entry("Undead Cape", "T4_CAPEITEM_UNDEAD"),
            Map.entry("Ursine Maulers", "T4_2H_KNUCKLES_KEEPER"),
            Map.entry("Wailing Bow", "T4_2H_BOW_HELL"),
            Map.entry("Warbow", "T4_2H_WARBOW"),
            Map.entry("Weeping Repeater", "T4_2H_REPEATINGCROSSBOW_UNDEAD"),
            Map.entry("Whispering Bow", "T4_2H_LONGBOW_UNDEAD"),
            Map.entry("Wild Staff", "T4_2H_WILDSTAFF"),
            Map.entry("Wildfire Staff", "T4_MAIN_FIRESTAFF_KEEPER"),
            Map.entry("Witchwork Staff", "T4_MAIN_ARCANESTAFF_UNDEAD"),
            Map.entry("Wood Axe", "T4_2H_TOOL_AXE")
    );

    private GearMarketItemData() {
    }

    public static String itemId(
            String displayName,
            int tier,
            int enchantment
    ) {
        if (displayName == null || displayName.isBlank()) {
            return null;
        }

        String baseId = BASE_IDS.get(displayName.trim());

        if (baseId == null || baseId.isBlank()) {
            return null;
        }

        String tiered = baseId.replaceFirst(
                "^T\\d+_",
                "T" + Math.max(1, tier) + "_"
        );

        if (enchantment <= 0) {
            int suffixIndex = tiered.indexOf('@');
            return suffixIndex >= 0
                    ? tiered.substring(0, suffixIndex)
                    : tiered;
        }

        int suffixIndex = tiered.indexOf('@');
        String cleanBase = suffixIndex >= 0
                ? tiered.substring(0, suffixIndex)
                : tiered;

        return cleanBase + "@" + enchantment;
    }
}
